# Generated by Django 5.2.7 on 2025-10-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='events_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_public',
            field=models.BooleanField(default=True),
        ),
    ]
