# Generated by Django 5.2.7 on 2025-10-05 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_age_visible_profile_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Unangemessener Inhalt'), ('harassment', 'Belästigung'), ('spam', 'Spam'), ('fake_profile', 'Falsches Profil'), ('violence', 'Gewalt'), ('other', 'Sonstiges')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('reviewed', 'Überprüft'), ('resolved', 'Gelöst'), ('dismissed', 'Abgewiesen')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter'], name='api_userrep_reporte_87a595_idx'), models.Index(fields=['reported_user'], name='api_userrep_reporte_8014b9_idx'), models.Index(fields=['status'], name='api_userrep_status_362cec_idx'), models.Index(fields=['reason'], name='api_userrep_reason_85e178_idx'), models.Index(fields=['status', 'created_at'], name='api_userrep_status_52907b_idx')],
                'unique_together': {('reporter', 'reported_user')},
            },
        ),
    ]
