# Generated by Django 5.2.7 on 2025-10-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
