# Generated by Django 5.2.7 on 2025-10-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.eventcomment'),
        ),
    ]
