"""
Django settings for eisenach_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Konfiguration importieren
try:
    from config import get_dev_config
    dev_config = get_dev_config()
except ImportError:
    # Fallback falls config.py nicht verfügbar
    dev_config = {
        'debug': True,
        'allowed_hosts': ['localhost', '127.0.0.1', '192.168.2.120'],
        'cors_allowed_origins': [
            'http://localhost:3000',
            'http://127.0.0.1:3000',
            'http://192.168.2.120:3000',
            'exp://192.168.2.120:8081',
        ]
    }

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vs@+6h@19aeqoir4acz&j+3n9%v%6!d_u4zvs0q_sqg&!zdy(4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = dev_config['debug']

# In der Entwicklung alle Hosts erlauben, damit wechselnde WLAN-IP-Adressen funktionieren
if dev_config.get('debug', True):
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = dev_config.get('allowed_hosts', [])

# Beim Serverstart kurze Hinweise ausgeben, welche URLs genutzt werden
api_base = dev_config.get('api_base_url', 'http://192.168.2.120:8000/api')
frontend_exp = dev_config.get('frontend_base_url', 'exp://192.168.2.120:8081')
frontend_web = dev_config.get('frontend_web_url', 'http://192.168.2.120:8081')
print(f"API: {api_base} | Frontend(Expo): {frontend_exp} | Frontend(Web): {frontend_web}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eisenach_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Custom Admin-Templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eisenach_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Use PostgreSQL in production/Docker, SQLite for local development
if os.getenv('DATABASE_URL'):
    # Docker/Production: Use PostgreSQL
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
    }
else:
    # Local development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files
STATICFILES_DIRS = []

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Konfiguration - definiert wie die API funktioniert
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Standard-Django-Anmeldung
        'rest_framework.authentication.TokenAuthentication',  # Token-basierte Anmeldung für mobile Apps
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Lesen für alle, Schreiben nur für angemeldete Benutzer
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # Seitenweise Anzeige
    'PAGE_SIZE': 20,  # 20 Einträge pro Seite
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',  # Für Datei-Uploads
        'rest_framework.parsers.FormParser',  # Für Form-Daten
    ],
}

# CORS-Konfiguration - erlaubt Anfragen vom Frontend
# Für wechselnde WLAN-Umgebungen in Entwicklung großzügig erlauben
if dev_config.get('debug', True):
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = dev_config.get('cors_allowed_origins', [])
else:
    CORS_ALLOWED_ORIGINS = dev_config['cors_allowed_origins']

CORS_ALLOW_CREDENTIALS = True  # Erlaubt das Senden von Cookies und Authentifizierungsdaten

# Erlaube Zugriffe aus privaten Netzwerken (für Mobilgerät im WLAN wichtig)
CORS_ALLOW_PRIVATE_NETWORK = True

# E-Mail Konfiguration (Yahoo SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.mail.yahoo.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'eisenachappverify@yahoo.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'Eisenachappverify24334')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
