/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/password-reset-confirm` | `/password-reset-confirm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/password-reset` | `/password-reset`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/friends` | `/friends`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `/events/manage`; params?: Router.UnknownInputParams; } | { pathname: `/friends/requests`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/events/dashboard/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/events/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/profile/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/password-reset-confirm` | `/password-reset-confirm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/password-reset` | `/password-reset`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/friends` | `/friends`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/upload` | `/upload`; params?: Router.UnknownOutputParams; } | { pathname: `/events/manage`; params?: Router.UnknownOutputParams; } | { pathname: `/friends/requests`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/event/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/events/dashboard/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/events/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/profile/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/password-reset-confirm${`?${string}` | `#${string}` | ''}` | `/password-reset-confirm${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/password-reset${`?${string}` | `#${string}` | ''}` | `/password-reset${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/friends${`?${string}` | `#${string}` | ''}` | `/friends${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/upload${`?${string}` | `#${string}` | ''}` | `/upload${`?${string}` | `#${string}` | ''}` | `/events/manage${`?${string}` | `#${string}` | ''}` | `/friends/requests${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/password-reset-confirm` | `/password-reset-confirm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/password-reset` | `/password-reset`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/friends` | `/friends`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/upload` | `/upload`; params?: Router.UnknownInputParams; } | { pathname: `/events/manage`; params?: Router.UnknownInputParams; } | { pathname: `/friends/requests`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | `/event/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/events/dashboard/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/events/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/profile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/events/dashboard/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/events/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/profile/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
